### ISSUE TITLE
Page is getting unlocked on wrong state when Marking workflow is enabled.

### ISSUE THREAD

**Issue by kabalin** [MaharaProject/moodle-assignfeedback_mahara#1]
Reported by Stephen Owens, learning technologist at Lancaster University:

_The unlocking functionality needs some work, at the moment it doesn’t seem to work with grading workflow i.e. no matter what state I change the grading workflow to the Mahara page gets unlocked, I’d only expect it to become unlocked when changed to ‘Released’. It appears to treat any change to the quick grading form as feedback and then unlocks in Mahara._

**Comment by agwells** [comment]
Hi Ruslan,

It appears the user's comments are referring to the "Grade -> Use marking workflow" feature of the assignment module. I had no idea this feature existed until I read this issue report! :)

I agree that it would make sense to release the assignment in Mahara only when the submission's "Status" in the gradebook is changed to "Released". Do you happen to know if the folks at Lancaster are working on implementing that functionality?

**Comment by kabalin** [comment]
Hi Aaron, we deployed it without feedback plugin at the moment. Updated version of assignsubmission_mahara with Portland uni code is working good BTW, thanks for working on that. We might have a look at fixing this one in the future, but it is not a priority at the moment.

**Comment by kabalin** [comment]
Ok, I investigated this in more details. It seem Quick grading does not play role here, thus I changed the title. The bug only appears when "Grade -> Use marking workflow" is enabled, as @agwells noticed, irrespective whether quick grading is in use or not. In fact, the plugin works correctly, as it does what it needs to do in response to grading action, but it does not take into account  "Marking workflow" state, which should suppress unlocking until the grade is released to student.

**Comment by kabalin** [comment]
Quick summary: Tracking workflow change is only possible via workflow_state_updated event (assuming we not modify Moodle core to trigger some function in feedback plugin when workflow is updated).

This brings me the question, whether unlocking should be performed in feedback plugin at all, which original purpose was to capture some "feedback" from grading teacher rather than perform a callback (that is what events are actually designed for). Elaborating this further brings up a question, whether this feedback plugin is needed? The solution to both, this issue and #2, can be adding events listeners to [moodle-assignsubmission_mahara](https://github.com/MaharaProject/moodle-assignsubmission_mahara) plugin to capture "grading" and "workflow" events and callback Mahara api accordingly. All grading data that is passed over to Mahara is available in events as well, so same outcomes array can be provided along with release_submitted_view call.

**Comment by kabalin** [comment]
Closing this, as issue has been resolved in 1.2 release of assignsubmission_mahara (https://github.com/MaharaProject/moodle-assignsubmission_mahara/releases/tag/release-1.2-2015021004)
